// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDElhmMlbhJrDT0yaq7sDGSUBwn8GvPvr0',
    appId: '1:667496523432:web:f6464d870261a52558849d',
    messagingSenderId: '667496523432',
    projectId: 'camping-ee9d0',
    authDomain: 'camping-ee9d0.firebaseapp.com',
    databaseURL: 'https://camping-ee9d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'camping-ee9d0.appspot.com',
    measurementId: 'G-49BF0TWN1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHKJ8gf40i9cuR5pLvx7Fjv9DtQDtIhY',
    appId: '1:667496523432:android:c0681195519a32df58849d',
    messagingSenderId: '667496523432',
    projectId: 'camping-ee9d0',
    databaseURL: 'https://camping-ee9d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'camping-ee9d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR_Jc2sOE7aNhfS7T5WS2b22eTXgTpiz4',
    appId: '1:667496523432:ios:99c2e0dd8901932558849d',
    messagingSenderId: '667496523432',
    projectId: 'camping-ee9d0',
    databaseURL: 'https://camping-ee9d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'camping-ee9d0.appspot.com',
    androidClientId: '667496523432-vllj1loc389qc45vfdo7e8oafqbl3m2l.apps.googleusercontent.com',
    iosClientId: '667496523432-7l0pm7aocpovik7im7uo1cnjq8e0umkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.yomate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR_Jc2sOE7aNhfS7T5WS2b22eTXgTpiz4',
    appId: '1:667496523432:ios:99c2e0dd8901932558849d',
    messagingSenderId: '667496523432',
    projectId: 'camping-ee9d0',
    databaseURL: 'https://camping-ee9d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'camping-ee9d0.appspot.com',
    androidClientId: '667496523432-vllj1loc389qc45vfdo7e8oafqbl3m2l.apps.googleusercontent.com',
    iosClientId: '667496523432-7l0pm7aocpovik7im7uo1cnjq8e0umkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.yomate',
  );
}
